version: "3.7"
services:
  provisioning:
    build:
      context: Dockerfile.d/provisioning
      args:
        UID: ${UID:-0}
        GID: ${GID:-0}
    command:
      - zsh
      - -ic
      - |
        echo ln -fs /project/config/$${CURRENT_ENV_NAME}/ansible.cfg $${HOME}/.ansible.cfg
    environment:
      ANSIBLE_CONFIG: /project/config/${CURRENT_ENV_NAME}/ansible.cfg
      CURRENT_ENV_NAME:
    user: "${UID:-0}:${GID:-0}"
    volumes:
      - provisioning-home-root:/root # for macOS
      - provisioning-home-developer:/home/developer
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.ssh:/root/.ssh:ro # for macOS
      - ${HOME}/.ssh:/developer/.ssh:ro
      - ./config:/project/config
      - ./provisioning:/project/workspace
    working_dir: /project/workspace
volumes:
  provisioning-home-root:
    driver: local
  provisioning-home-developer:
    driver: local
