- name: Set up wheel group on Debian and Ubuntu
  block:
    - name: Uncomment the wheel line in /etc/pam.d/su
      lineinfile:
        dest: /etc/pam.d/su
        regexp: '^\s*#\s+auth\s+sufficient\s+pam_wheel.so\s+trust\s*$'
        line: "auth       sufficient pam_wheel.so trust"
    - name: Create the wheel group
      ansible.builtin.group:
        name: wheel
        system: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Create the user
  ansible.builtin.user:
    name: "{{ default_user_name }}"
    uid: "{{ default_user_uid }}"
    shell: /bin/zsh
    group: users
    groups: docker,wheel
    generate_ssh_key: true

- name: Set up shell
  block:
    - name: Install packages
      ansible.builtin.package:
        name:
          - zsh
        state: latest
    - name: Install starship
      shell: >
        curl -sS https://starship.rs/install.sh | sh -s -- --yes
      args:
        creates: /usr/local/bin/starship
  # tags:
  #   - debug_current

- name: Apply templates
  block:
    - name: Create directories by the templates
      file:
        path: "{{ item | regex_replace('^('+role_path+'/templates/)(.*)', \"/\\2\") }}"
        state: directory
      with_lines: find {{ role_path }}/templates -type d
    - name: Apply templates
      template:
        dest: "{{ item | regex_replace('^('+role_path+'/templates/)(.*)(.j2$)', \"/\\2\") }}"
        src: "{{ item }}"
      with_lines: find {{ role_path }}/templates -type f -name '*.j2'
