# Packages
- name: Install Packages - Gentoo
  import_tasks: linux.gentoo.packages.yml
  when:
    - ansible_facts.system == "Linux"
    - ansible_facts.distribution == 'Gentoo'
- name: Install Packages - Ubuntu
  import_tasks: linux.ubuntu.packages.yml
  when:
    - ansible_facts.system == "Linux"
    - ansible_facts.distribution == 'Ubuntu'
