# - name: whoami
#   # become_user: "{{ default_user_name }}"
#   # become: true
#   # become: false
#   block:
#     - name: id
#       shell: >
#         id
#       changed_when: false
#       register: _debug_id
#     - debug:
#         msg: "{{ _debug_id }}"
#
- name: Set up shell
  block:
    - name: Get the homedir
      shell: >
        getent passwd {{ default_user_name }} | cut -d: -f6
      changed_when: false
      register: default_user_homedir
    - name: Touch the empty zshrc file
      ansible.builtin.file:
        path: "{{ default_user_homedir.stdout }}/.zshrc"
        state: touch
        mode: u=rx,g=r,o=r
        modification_time: preserve
        access_time: preserve
    - debug:
        msg: "{{ default_user_homedir }}"
